git-ups improvments
Signed-off-by: Alex Hokanson <571756+ingshtrom@users.noreply.github.com>

diff --git a/bin/git-ups b/bin/git-ups
--- a/bin/git-ups
+++ b/bin/git-ups
@@ -24,25 +24,32 @@ then
     exit 1
 fi
 
+MAIN_BRANCH='unknown'
+
 # if we are not on main/master, then switch to it
 # we already know we do not have changes in our current branch
 if ! ( git branch | grep -E '\* (main|master)' 2>&1 > /dev/null )
 then
     if git branch | grep 'main'; then
-        git checkout main
-        git merge upstream/main --no-log
+        MAIN_BRANCH='main'
     elif git branch | grep 'master'; then
-        git checkout master
-        git merge upstream/master --no-log
-    else
-        echo "main or master not found in branch listing"
-        exit 1
+        MAIN_BRANCH='master'
     fi
 fi
 
-echo "Log:"
-git log --color --pretty=tformat:'%C(yellow)%h %C(red)%an %C(reset)%s' --abbrev-commit HEAD@{1}.. | sed 's/^/  /'
+if [[ "$MAIN_BRANCH" == "unknown" ]] then
+    echo "main or master not found in branch listing"
+    exit 1
+fi
+
+git checkout "$MAIN_BRANCH"
+echo
+echo "EASY CHANGELOG:"
+git log --color --pretty=tformat:'%C(yellow)%h %C(red)%an %C(reset)%s' --abbrev-commit upstream/main..HEAD | sed 's/^/  /'
+echo
+echo "RAW CHANGELOG:"
+git merge "upstream/${MAIN_BRANCH}" --no-log
 
 # make sure our forked main/master is up to date with the latest changes too
-#git push
+git push
 
